# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Let's get Person-al
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  a brainforest
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: person72443
github_username:  its-person-time
goat_counter: person
disclaimer: Every post on this blog is a work in progress. Phrasing may be less than ideal, ideas may not yet be fully thought through. Thank you for watching me grow.

# Build settings
theme: no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%a %d %b %Y" # customize how date is formatted
  home_date_format: "%Y.%m.%d" # customize how date is formatted
  show_description: false # show blog description in home page

plugins:
  - jekyll-feed

feed:
  categories:
    - ❔
    - 🌰
    - 🌱
    - 🌳
    - 🌲

vault:
  path: "_vault/" # Path to the Obsidian vault root. Markdown file discovery will start at this directory recursively.
  asset_path: "_vault/assets/" # Path to the Obsidian vault attachments folder
  excluded_subdirectories: # Optional: list of excluded subdirectories of the Obsidian vault root
          - .trash
          - .obsidian
          - templates
output:
  post_output_path: "_posts/" # Path to the Jekyll or Hugo posts directory
  asset_output_path: "assets/" # Path to the blog assets directory, copied from the Obsidian attachments folder
  relative_asset_path_prefix: "{{ site.blog_assets_location }}" # Optional: a relative URL prefix for blog assets without a trailing slash. Can also be a liquid template substitution for Jekyll.
  post_link_mode: "jekyll" # Optional, values can be either "jekyll" or "hugo" and the default is "jekyll". Sets the way post references are output.


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/